import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleTagManager } from '@next/third-parties/google'
import StyledJsxRegistry from './registry'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chad Vogel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <GoogleTagManager gtmId="GTM-NHB"/>
      <StyledJsxRegistry>{children}</StyledJsxRegistry>
      </body>
      </html>
  );
}
